### ISSUE TITLE
disable chat distortion

### ISSUE THREAD

**Issue by random1167** [DieReicheErethons/Brewery#125]
In your next update can you please add in a way to disable chat distortion .. we love this plugin but our players are super spammy lol
i have removed all commands but /wisper in the distortCommands section of the config
adding or editing ` '' ','` in the bypass section works but spams the console with the error below
```
Could not pass event AsyncPlayerChatEvent to Brewery v1.4.4
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-106ced0]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-106ced0]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.4.jar:git-Spigot-8a048fe-106ced0]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.9.4.jar:git-Spigot-8a048fe-106ced0]
        at net.minecraft.server.v1_9_R2.PlayerConnection.chat(PlayerConnection.java:1271) [spigot-1.9.4.jar:git-Spigot-8a048fe-106ced0]
        at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1209) [spigot-1.9.4.jar:git-Spigot-8a048fe-106ced0]
        at net.minecraft.server.v1_9_R2.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot-1.9.4.jar:git-Spigot-8a048fe-106ced0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_77]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_77]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_77]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_77]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
        at com.dre.brewery.Words.distortMessage(Words.java:151) ~[?:?]
        at com.dre.brewery.Words.playerChat(Words.java:137) ~[?:?]
        at com.dre.brewery.listeners.PlayerListener.onPlayerChat(PlayerListener.java:221) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_77]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-106ced0]
        ... 11 more
```

**Comment by Sn0wStorm** [comment]
Yes that would be a good idea to add a way to disable that.
