### ISSUE TITLE
Failed to Check WorldGuard for Barrel Open Permissions!

### ISSUE THREAD

**Issue by kelso6969** [DieReicheErethons/Brewery#175]
latest spigot
worldguard: worldguard-legacy-7.0.0-SNAPSHOT-dist.jar (recent snapshot)

[09:38:48] [Server thread/INFO]: ^[[0;32;22m[Brewery] ^[[0;31;22mERROR: ^[[0;31;1mFailed to Check WorldGuard for Barrel Open Permissions!^[[m
[09:38:48] [Server thread/INFO]: ^[[0;32;22m[Brewery] ^[[0;31;22mERROR: ^[[0;31;1mBrewery was tested with version 5.8 to 6.1 of WorldGuard!^[[m
[09:38:48] [Server thread/INFO]: ^[[0;32;22m[Brewery] ^[[0;31;22mERROR: ^[[0;31;1mDisable the WorldGuard support in the config and do /brew reload^[[m
[09:38:48] [Server thread/WARN]: java.lang.NoSuchMethodError: com.sk89q.worldguard.internal.platform.WorldGuardPlatform.getWorldByName(Ljava/lang/String;)Lcom/sk89q/worldedit/world/World;
[09:38:48] [Server thread/WARN]:        at com.dre.brewery.integration.WGBarrel7.checkAccess(WGBarrel7.java:26)
[09:38:48] [Server thread/WARN]:        at com.dre.brewery.Barrel.hasPermsOpen(Barrel.java:124)
[09:38:48] [Server thread/WARN]:        at com.dre.brewery.listeners.PlayerListener.onPlayerInteract(PlayerListener.java:170)
[09:38:48] [Server thread/WARN]:        at sun.reflect.GeneratedMethodAccessor310.invoke(Unknown Source)
[09:38:48] [Server thread/WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:38:48] [Server thread/WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[09:38:48] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305)
[09:38:48] [Server thread/WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[09:38:48] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[09:38:48] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[09:38:48] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:299)
[09:38:48] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:466)
[09:38:48] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1237)
[09:38:48] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
[09:38:48] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1)
[09:38:48] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
[09:38:48] [Server thread/WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[09:38:48] [Server thread/WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[09:38:48] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[09:38:48] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896)
[09:38:48] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[09:38:48] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[09:38:48] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[09:38:48] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:748)

**Comment by Sataniel98** [comment]
Yeah, I programmed the integration for WorldEdit and WorldGuard 7 before it was actually released. There have been breaking changes since then, and I am in this moment trying to figure out how things are to be done now.
