### ISSUE TITLE
1.14.3 Error 

### ISSUE THREAD

**Issue by Silmarost** [DieReicheErethons/Brewery#192]
Hello,
I'm in 1.14.3 and i have this error that occure when i start my server and sometimes when my players play (moreover I often have it twice in a row) , i don't understand why i have it. Thank you in advance for your answer.

[11:03:38] [Server thread/WARN]: [Brewery] Task #1831 for Brewery v1.7.2 generated an exception
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429) ~[?:1.8.0_72]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1453) ~[?:1.8.0_72]
	at java.lang.Iterable.forEach(Iterable.java:74) ~[?:1.8.0_72]
	at net.minecraft.server.v1_14_R1.ChunkMapDistance.a(ChunkMapDistance.java:102) ~[spigot-1.14.3.jar:git-Spigot-5e4e7f3-5f88938]
	at net.minecraft.server.v1_14_R1.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:202) ~[spigot-1.14.3.jar:git-Spigot-5e4e7f3-5f88938]
	at net.minecraft.server.v1_14_R1.ChunkProviderServer.getChunkFutureMainThread(ChunkProviderServer.java:142) ~[spigot-1.14.3.jar:git-Spigot-5e4e7f3-5f88938]
	at net.minecraft.server.v1_14_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:89) ~[spigot-1.14.3.jar:git-Spigot-5e4e7f3-5f88938]
	at net.minecraft.server.v1_14_R1.IChunkProvider.getChunkAt(SourceFile:16) ~[spigot-1.14.3.jar:git-Spigot-5e4e7f3-5f88938]
	at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.getChunkAt(CraftWorld.java:328) ~[spigot-1.14.3.jar:git-Spigot-5e4e7f3-5f88938]
	at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.getChunkAt(CraftWorld.java:333) ~[spigot-1.14.3.jar:git-Spigot-5e4e7f3-5f88938]
	at org.bukkit.craftbukkit.v1_14_R1.block.CraftBlock.getChunk(CraftBlock.java:125) ~[spigot-1.14.3.jar:git-Spigot-5e4e7f3-5f88938]
	at com.dre.brewery.Barrel.getBrokenBlock(Barrel.java:694) ~[?:?]
	at com.dre.brewery.Barrel$BarrelCheck.run(Barrel.java:876) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.3.jar:git-Spigot-5e4e7f3-5f88938]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.14.3.jar:git-Spigot-5e4e7f3-5f88938]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1011) [spigot-1.14.3.jar:git-Spigot-5e4e7f3-5f88938]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.3.jar:git-Spigot-5e4e7f3-5f88938]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:959) [spigot-1.14.3.jar:git-Spigot-5e4e7f3-5f88938]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:804) [spigot-1.14.3.jar:git-Spigot-5e4e7f3-5f88938]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

**Comment by Sn0wStorm** [comment]
Fixed in e123f32728c6aaf11379f1bb785a62714d8f69cc
