### ISSUE TITLE
Error in the console at the server boot

### ISSUE THREAD

**Issue by Katalijst** [DieReicheErethons/Brewery#230]
`03:03:19: [Brewery] Plugin Brewery v2.0.1 generated an exception while executing task 77
java.lang.IllegalStateException: This is not a JSON Array.
at com.google.gson.JsonElement.getAsJsonArray(JsonElement.java:106) ~[patched_1.14.4.jar:git-Paper-236]
at com.dre.brewery.filedata.UpdateChecker.query(UpdateChecker.java:88) ~[?:?]
at com.dre.brewery.filedata.UpdateChecker.run(UpdateChecker.java:50) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-236]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-236]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-236]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]`

I get this at every boot of the server, I don't know if it's because of my server or not.

**Comment by Sn0wStorm** [comment]
This is an error regarding the Plugin Updater, maybe something on the Bukkit Server broke. Its not happening for me
