### ISSUE TITLE
NoSuchMethodError: 'net.mmogroup.mmolib.version.nms.NMSHandler net.mmogroup.mmolib.MMOLib.getNMS()'

### ISSUE THREAD

**Issue by mibby** [DieReicheErethons/Brewery#329]
Incompatible with MMOLib 1.3.5?

```
[14:23:31] [Server thread/WARN]: [Brewery] Loaded class net.mmogroup.mmolib.MMOLib from MMOLib v1.3.5 which is not a depend, softdepend or loadbefore of this plugin.
[14:23:31] [Server thread/INFO]: [Brewery] ERROR: Could not check MMOItems for Item
[14:23:31] [Server thread/WARN]: java.lang.NoSuchMethodError: 'net.mmogroup.mmolib.version.nms.NMSHandler net.mmogroup.mmolib.MMOLib.getNMS()'
[14:23:31] [Server thread/WARN]: 	at com.dre.brewery.integration.IntegrationListener.onInteract(IntegrationListener.java:231)
[14:23:31] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1189.execute(Unknown Source)
[14:23:31] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[14:23:31] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[14:23:31] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[14:23:31] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[14:23:31] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:503)
[14:23:31] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.PlayerInteractManager.a(PlayerInteractManager.java:497)
[14:23:31] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1462)
[14:23:31] [Server thread/WARN]: 	at xuan.cat.xuancatapi.code.v1_16_R2.nms.entity.CodeExtendPlayerConnection.packetIn(CodeExtendPlayerConnection.java:765)
[14:23:31] [Server thread/WARN]: 	at xuan.cat.xuancatapi.code.v1_16_R2.nms.entity.CodeExtendPlayerConnection.packetIn(CodeExtendPlayerConnection.java:604)
[14:23:31] [Server thread/WARN]: 	at xuan.cat.xuancatapi.code.v1_16_R2.nms.entity.CodeExtendPlayerConnection.a(CodeExtendPlayerConnection.java:112)
[14:23:31] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27)
[14:23:31] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5)
[14:23:31] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43)
[14:23:31] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18)
[14:23:31] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[14:23:31] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[14:23:31] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[14:23:31] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1192)
[14:23:31] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1185)
[14:23:31] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[14:23:31] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1260)
[14:23:31] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1001)
[14:23:31] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:178)
[14:23:31] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by Sn0wStorm** [comment]
Should be fixed here 1aae3340a333361ddf21ea7197414a83662edd31
