### ISSUE TITLE
Brewery/MMOItem ERROR: Could not check MMOItems for Item

### ISSUE THREAD

**Issue by Monurisis** [DieReicheErethons/Brewery#384]
Hallöchen,

vorneweg, ein wirklich tolles Plugin! Super Arbeit! :-)

Wir nutzen es neuerdings im Zusammenhang mit MMOItems, was die Bandbreite an Möglichkeiten erhöht und den Spielspaß steigert. Seit letztem Wochenende bekommen wir allerdings eine Fehlermeldung. Die Console spuckt folgenden Text aus:

```
11:35:24 [Brewery]: ERROR: Could not check MMOItems for Item
WARN 11:35:24
 java.lang.NoClassDefFoundError: net/mmogroup/mmolib/api/item/NBTItem
at com.dre.brewery.integration.IntegrationListener.onInteract(IntegrationListener.java:327)
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor545.execute(Unknown Source)
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:511)
at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:497)
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1635)
at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27)
at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5)
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43)
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1206)
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1199)
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1175)
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1019)
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.mmogroup.mmolib.api.item.NBTItem
at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:182)
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111)
at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
... 23 more
```

Seit dem kann man die Custom Items auch nicht mehr dem Kessel hinzufügen. Aus dem Consolen Output kann ich leider nicht viel rauslesen, schätze aber dass es im Zusammenhang mit einem MMOItem Update liegt und evtl. Brewery nicht mehr richtig die MMOItem Daten auslesen kann? Ist euch das Problem bereits?

Beste Grüße
Monurisis

**Comment by Sn0wStorm** [comment]
Hm vielleicht haben die bei MMOItems schon wieder ihre api geändert, danke da muss ich mal nachschauen

**Comment by Sn0wStorm** [comment]
Will be fixed in the new version, they are now using MythicLib instead of MMOLib
