### ISSUE TITLE
Brewery is not compatible with the latest Slimefun. 

### ISSUE THREAD

**Issue by XXY233** [DieReicheErethons/Brewery#437]
```
[18:56:20] [Server thread/WARN]: java.lang.NoClassDefFoundError: me.mrCookieSlime.Slimefun.Objects.SlimefunItem.SlimefunItem
[18:56:20] [Server thread/WARN]: 	at B[啤酒厂]Brewery-3.1.jar//com.dre.brewery.integration.item.SlimefunPluginItem.matches(SlimefunPluginItem.java:24)
[18:56:20] [Server thread/WARN]: 	at B[啤酒厂]Brewery-3.1.jar//com.dre.brewery.recipe.RecipeItem.getMatchingRecipeItem(RecipeItem.java:147)
[18:56:20] [Server thread/WARN]: 	at B[啤酒厂]Brewery-3.1.jar//com.dre.brewery.BCauldron.ingredientAdd(BCauldron.java:140)
[18:56:20] [Server thread/WARN]: 	at B[啤酒厂]Brewery-3.1.jar//com.dre.brewery.BCauldron.clickCauldron(BCauldron.java:462)
[18:56:20] [Server thread/WARN]: 	at B[啤酒厂]Brewery-3.1.jar//com.dre.brewery.listeners.PlayerListener.onPlayerInteract(PlayerListener.java:76)
[18:56:20] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor614.execute(Unknown Source)
[18:56:20] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[18:56:20] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$$Lambda$5766/0x0000000081360918.execute(Unknown Source)
[18:56:20] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[18:56:20] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[18:56:20] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[18:56:20] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:542)
[18:56:20] [Server thread/WARN]: 	at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:542)
[18:56:20] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1801)
[18:56:20] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:33)
[18:56:20] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9)
[18:56:20] [Server thread/WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[18:56:20] [Server thread/WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils$$Lambda$8208/0x0000000086e3dce8.run(Unknown Source)
[18:56:20] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[18:56:20] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[18:56:20] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[18:56:20] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1418)
[18:56:20] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192)
[18:56:20] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[18:56:20] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1396)
[18:56:20] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1389)
[18:56:20] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[18:56:20] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1367)
[18:56:20] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1278)
[18:56:20] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[18:56:20] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer$$Lambda$3664/0x00000000fe62b410.run(Unknown Source)
[18:56:20] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:883)
[18:56:20] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: me.mrCookieSlime.Slimefun.Objects.SlimefunItem.SlimefunItem
[18:56:20] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146)
[18:56:20] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[18:56:20] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1111)
[18:56:20] [Server thread/WARN]: 	... 32 more
[18:56:20] [Server thread/INFO]: [Brewery] ERROR: Could not check Slimefun for Item ID
```

**Comment by ReasonFoundDecoy** [comment]
Still nothing yet? It's been 5 months, starting to wonder if I should even check anymore

**Comment by satanplaysmc** [comment]
any update on this bug yet? Slimefun ingredients are vital to a lot of drinks.

**Comment by ReasonFoundDecoy** [comment]
Yes, they *just* updated last week! 
https://www.spigotmc.org/resources/brewery.3082/updates
I'm not sure how to mark this as closed or if the person has to do it, but this isn't a valid report any longer.
