### ISSUE TITLE
Magma Compatibility?

### ISSUE THREAD

**Issue by Kikithecat12345** [DieReicheErethons/Brewery#445]
I have been unable to make this plugin work with the 1.16.5 versions of Magma. I have tried:
* Changing java versions
* Reinstalling Magma and Brewery
* Google Searches
The console for the server shows this:
```
[12:18:28] [Server thread/INFO] [co.dr.br.P/]: [Brewery] Enabling Brewery v3.1
[12:18:29] [Server thread/WARN] [/]: java.lang.UnsupportedOperationException
[12:18:29] [Server thread/WARN] [/]:    at com.google.common.collect.ImmutableMap.put(ImmutableMap.java:473)
[12:18:29] [Server thread/WARN] [/]:    at net.minecraft.item.crafting.RecipeManager.addRecipe(RecipeManager.java:88)
[12:18:29] [Server thread/WARN] [/]:    at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftShapedRecipe.addToCraftingManager(CraftShapedRecipe.java:58)
[12:18:29] [Server thread/WARN] [/]:    at org.bukkit.craftbukkit.v1_16_R3.CraftServer.addRecipe(CraftServer.java:1100)
[12:18:29] [Server thread/WARN] [/]:    at com.dre.brewery.BSealer.registerRecipe(BSealer.java:153)
[12:18:29] [Server thread/WARN] [/]:    at com.dre.brewery.filedata.BConfig.readConfig(BConfig.java:361)
[12:18:29] [Server thread/WARN] [/]:    at com.dre.brewery.P.onEnable(P.java:121)
[12:18:29] [Server thread/WARN] [/]:    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[12:18:29] [Server thread/WARN] [/]:    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[12:18:29] [Server thread/WARN] [/]:    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[12:18:29] [Server thread/WARN] [/]:    at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:492)
[12:18:29] [Server thread/WARN] [/]:    at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:406)
[12:18:29] [Server thread/WARN] [/]:    at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:485)
[12:18:29] [Server thread/WARN] [/]:    at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:404)
[12:18:29] [Server thread/WARN] [/]:    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:253)
[12:18:29] [Server thread/WARN] [/]:    at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:826)
[12:18:29] [Server thread/WARN] [/]:    at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:286)
[12:18:29] [Server thread/WARN] [/]:    at java.base/java.lang.Thread.run(Unknown Source)
[12:18:29] [Server thread/INFO] [co.dr.br.P/]: [Brewery] Disabling Brewery v3.1
```
The server starts fine, but without Brewery.

**Comment by Sn0wStorm** [comment]
Servers other than Spigot or Paper are not supported. It may work or it may not.
Try disabling `craftSealingTable`
