### ISSUE TITLE
Question: How does one use MMOItems as an ingredient using the config?

### ISSUE THREAD

**Issue by Snowy2174** [DieReicheErethons/Brewery#451]
The default config implies the use of '_plugin:id_' but on attempting **MMOItems:MANGO/1** it returns an error, what would be the proper way to format it?

**Comment by JoloJanssen** [comment]
I have the same question for the ExoticGarden addon for slimefun. While I do not get an error i instead can't place the item in the cauldron. What would be the correct formatting?

**Comment by humanhen** [comment]
Yeah same when I do /itemname on lets say a strawberry in exoticgarden it says player_head

**Comment by JoloJanssen** [comment]
> I have the same question for the ExoticGarden addon for slimefun. While I do not get an error i instead can't place the item in the cauldron. What would be the correct formatting?

When i try to spam a grape on a cauldron (grape brew and cauldron "must" do exist)
The Error i get is as follows:
[16:09:07] [Server thread/WARN]: java.lang.NoClassDefFoundError: me/mrCookieSlime/Slimefun/Objects/SlimefunItem/SlimefunItem
[16:09:07] [Server thread/WARN]: 	at com.dre.brewery.integration.item.SlimefunPluginItem.matches(SlimefunPluginItem.java:24)
[16:09:07] [Server thread/WARN]: 	at com.dre.brewery.recipe.RecipeItem.getMatchingRecipeItem(RecipeItem.java:147)
[16:09:07] [Server thread/WARN]: 	at com.dre.brewery.BCauldron.ingredientAdd(BCauldron.java:140)
[16:09:07] [Server thread/WARN]: 	at com.dre.brewery.BCauldron.clickCauldron(BCauldron.java:462)
[16:09:07] [Server thread/WARN]: 	at com.dre.brewery.listeners.PlayerListener.onPlayerInteract(PlayerListener.java:76)
[16:09:07] [Server thread/WARN]: 	at jdk.internal.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
[16:09:07] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:09:07] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[16:09:07] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[16:09:07] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[16:09:07] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
[16:09:07] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
[16:09:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:504)
[16:09:07] [Server thread/WARN]: 	at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:484)
[16:09:07] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1534)
[16:09:07] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:33)
[16:09:07] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1)
[16:09:07] [Server thread/WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30)
[16:09:07] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(SourceFile:18)
[16:09:07] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:151)
[16:09:07] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(SourceFile:23)
[16:09:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1158)
[16:09:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:1)
[16:09:07] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.y(SourceFile:125)
[16:09:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1137)
[16:09:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1130)
[16:09:07] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:134)
[16:09:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1114)
[16:09:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1038)
[16:09:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[16:09:07] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[16:09:07] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: me.mrCookieSlime.Slimefun.Objects.SlimefunItem.SlimefunItem
[16:09:07] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147)
[16:09:07] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
[16:09:07] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[16:09:07] [Server thread/WARN]: 	... 31 more
[16:09:07] [Server thread/INFO]: [0;32;22m[Brewery] [0;31;22mERROR: [0;31;1mCould not check Slimefun for Item ID[m
