### ISSUE TITLE
[WARN]: [Brewery] Plugin Brewery v3.1.1 generated an exception while executing task 259

### ISSUE THREAD

**Issue by DENPOY** [DieReicheErethons/Brewery#494]
Plugin Brewery v3.1.1 generated an exception while executing task 259
java.lang.NoSuchMethodError: 'com.google.gson.JsonElement com.google.gson.JsonParser.parseReader(java.io.Reader)'
        at com.dre.brewery.filedata.UpdateChecker.query(UpdateChecker.java:85) ~[?:?]
        at com.dre.brewery.filedata.UpdateChecker.run(UpdateChecker.java:50) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-794]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-794]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by DENPOY** [comment]
Okey...................... i don't have support?

**Comment by Faustyu1** [comment]
up
