### ISSUE TITLE
brewery bug error in console

### ISSUE THREAD

**Issue by Faustyu1** [DieReicheErethons/Brewery#533]
Plugin Brewery v3.1.1 generated an exception while executing task 47
java.lang.NoSuchMethodError: 'com.google.gson.JsonElement com.google.gson.JsonParser.parseReader(java.io.Reader)'
        at com.dre.brewery.filedata.UpdateChecker.query(UpdateChecker.java:85) ~[?:?]
        at com.dre.brewery.filedata.UpdateChecker.run(UpdateChecker.java:50) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Patina-ver/1.16.5-"667fb1b"]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.5.jar:git-Patina-ver/1.16.5-"667fb1b"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Patina-ver/1.16.5-"667fb1b"]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]

**Comment by DovahThuri** [comment]
If there is an error, then there is likely something that isn't formatted correctly in the config.
