### ISSUE TITLE
it have error in 1.20.1 folia but it can be use

### ISSUE THREAD

**Issue by BallkingCN** [DieReicheErethons/Brewery#593]
the error log is full of my console and repeat it

�[09:13:17 WARN]: [Brewery] Global task for Brewery v3.1.1 generated an exception
java.lang.IllegalStateException: Cannot read world asynchronously
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:60) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at org.bukkit.craftbukkit.v1_20_R1.block.CraftBlock.getNMS(CraftBlock.java:84) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at org.bukkit.craftbukkit.v1_20_R1.block.CraftBlockStates.getBlockState(CraftBlockStates.java:239) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at org.bukkit.craftbukkit.v1_20_R1.block.CraftBlockStates.getBlockState(CraftBlockStates.java:231) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at org.bukkit.craftbukkit.v1_20_R1.block.CraftBlock.getState(CraftBlock.java:347) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at com.dre.brewery.BDistiller$DistillRunnable.run(BDistiller.java:176) ~[Brewery-3.1.1-folia.jar:?]
        at com.dre.brewery.integration.universalScheduler.foliaScheduler.FoliaScheduler.lambda$runTaskTimer$2(FoliaScheduler.java:63) ~[Brewery-3.1.1-folia.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[kaiiju-1.20.1.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[kaiiju-1.20.1.jar:?]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:294) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:149) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
�[09:13:17 ERROR]: Thread Region Scheduler Thread #0 failed main thread check: Cannot read world asynchronously
java.lang.Throwable: null
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:59) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at org.bukkit.craftbukkit.v1_20_R1.block.CraftBlock.getNMS(CraftBlock.java:84) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at org.bukkit.craftbukkit.v1_20_R1.block.CraftBlockStates.getBlockState(CraftBlockStates.java:239) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at org.bukkit.craftbukkit.v1_20_R1.block.CraftBlockStates.getBlockState(CraftBlockStates.java:231) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at org.bukkit.craftbukkit.v1_20_R1.block.CraftBlock.getState(CraftBlock.java:347) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at com.dre.brewery.BDistiller$DistillRunnable.run(BDistiller.java:176) ~[Brewery-3.1.1-folia.jar:?]
        at com.dre.brewery.integration.universalScheduler.foliaScheduler.FoliaScheduler.lambda$runTaskTimer$2(FoliaScheduler.java:63) ~[Brewery-3.1.1-folia.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[kaiiju-1.20.1.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[kaiiju-1.20.1.jar:?]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:294) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:149) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by TheXiaoma** [comment]
You can try to rebuild it yourself, it was only committed 4 days ago

**Comment by BallkingCN** [comment]
> You can try to rebuild it yourself, it was only committed 4 days ago

its still does work

![E`UMCQD$86$9@4EN5%T%RBK](https://github.com/DieReicheErethons/Brewery/assets/147357460/5400f456-7adb-4a5e-9706-293f07e30223)
