### ISSUE TITLE
java.io.FileNotFoundException: plugins/Brewery/data.yml (Permission denied)

### ISSUE THREAD

**Issue by dol4iua** [DieReicheErethons/Brewery#616]
[14:21:43 WARN]: java.io.FileNotFoundException: plugins/Brewery/data.yml (Permission denied)
[14:21:43 WARN]:        at java.base/java.io.FileOutputStream.open0(Native Method)
[14:21:43 WARN]:        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
[14:21:43 WARN]:        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
[14:21:43 WARN]:        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
[14:21:43 WARN]:        at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:67)
[14:21:43 WARN]:        at Brewery-3.1.1.jar//com.dre.brewery.filedata.WriteData.run(WriteData.java:29)
[14:21:43 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[14:21:43 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[14:21:43 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[14:21:43 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[14:21:43 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[14:21:43 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
Purpur 1.20.1

**Comment by dol4iua** [comment]
Fixed , my bed
