### ISSUE TITLE
[Brewery] Task #9 for Brewery v3.1.1 generated an exception

### ISSUE THREAD

**Issue by CutieAshlynn** [DieReicheErethons/Brewery#631]
[15:53:32] [Server thread/WARN]: [Brewery] Task #9 for Brewery v3.1.1 generated an exception
java.lang.IllegalArgumentException: missing required data class org.bukkit.Color
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:218) ~[guava-32.1.2-jre.jar:?]
	at org.bukkit.craftbukkit.CraftParticle.createParticleParam(CraftParticle.java:68) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at org.bukkit.craftbukkit.CraftWorld.spawnParticle(CraftWorld.java:2176) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at org.bukkit.craftbukkit.CraftWorld.spawnParticle(CraftWorld.java:2164) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at org.bukkit.craftbukkit.CraftWorld.spawnParticle(CraftWorld.java:2153) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at org.bukkit.craftbukkit.CraftWorld.spawnParticle(CraftWorld.java:2143) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at org.bukkit.craftbukkit.CraftWorld.spawnParticle(CraftWorld.java:2138) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at Brewery-3.1.1.jar/com.dre.brewery.BCauldron.cookEffect(BCauldron.java:257) ~[Brewery-3.1.1.jar:?]
	at Brewery-3.1.1.jar/com.dre.brewery.BCauldron.processCookEffects(BCauldron.java:375) ~[Brewery-3.1.1.jar:?]
	at Brewery-3.1.1.jar/com.dre.brewery.P$CauldronParticles.run(P.java:426) ~[Brewery-3.1.1.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1689) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:507) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1573) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1275) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

Is getting spammed in the console endlessly.

**Comment by Jsinco** [comment]
Fixed in BreweryX https://github.com/Jsinco/BreweryX
