### ISSUE TITLE
Console Spam Error?

### ISSUE THREAD

**Issue by Grrevous** [DieReicheErethons/Brewery#639]
I figure that this is popping up and spamming my console because I don't have a 'cookparticles' on the recipes, but I have no clear idea. If you have any pointers that'd be nice.

"[18:17:34 WARN]: [Brewery] Task #109 for Brewery v3.1.1 generated an exception
java.lang.IllegalArgumentException: missing required data class org.bukkit.Color
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:218) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.craftbukkit.CraftParticle.createParticleParam(CraftParticle.java:68) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at org.bukkit.craftbukkit.CraftWorld.spawnParticle(CraftWorld.java:2262) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at org.bukkit.craftbukkit.CraftWorld.spawnParticle(CraftWorld.java:2250) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at org.bukkit.craftbukkit.CraftWorld.spawnParticle(CraftWorld.java:2239) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at org.bukkit.craftbukkit.CraftWorld.spawnParticle(CraftWorld.java:2229) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at org.bukkit.craftbukkit.CraftWorld.spawnParticle(CraftWorld.java:2224) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at Brewery-3.1.1.jar/com.dre.brewery.BCauldron.cookEffect(BCauldron.java:257) ~[Brewery-3.1.1.jar:?]
        at Brewery-3.1.1.jar/com.dre.brewery.BCauldron.processCookEffects(BCauldron.java:375) ~[Brewery-3.1.1.jar:?]
        at Brewery-3.1.1.jar/com.dre.brewery.P$CauldronParticles.run(P.java:426) ~[Brewery-3.1.1.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1699) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1571) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]"

**Comment by Ownercz** [comment]
Hi,
same here, running on 1.21.1 latest Paper release.
```

[12:34:20] [Server thread/INFO]: This server is running Paper version 1.21.1-57-master@b483da4 (2024-09-01T18:09:05Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-496 (MC: 1.20.4)
[12:34:21] [Server thread/WARN]: [Brewery] Task #180 for Brewery v3.1.1 generated an exception
java.lang.IllegalArgumentException: missing required data class org.bukkit.Color
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:218) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.craftbukkit.CraftParticle.createParticleParam(CraftParticle.java:68) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at org.bukkit.craftbukkit.CraftWorld.spawnParticle(CraftWorld.java:2181) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at org.bukkit.craftbukkit.CraftWorld.spawnParticle(CraftWorld.java:2169) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at org.bukkit.craftbukkit.CraftWorld.spawnParticle(CraftWorld.java:2158) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at org.bukkit.craftbukkit.CraftWorld.spawnParticle(CraftWorld.java:2148) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at org.bukkit.craftbukkit.CraftWorld.spawnParticle(CraftWorld.java:2143) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at Brewery-3.1.1.jar/com.dre.brewery.BCauldron.cookEffect(BCauldron.java:257) ~[Brewery-3.1.1.jar:?]
        at Brewery-3.1.1.jar/com.dre.brewery.BCauldron.processCookEffects(BCauldron.java:375) ~[Brewery-3.1.1.jar:?]
        at Brewery-3.1.1.jar/com.dre.brewery.P$CauldronParticles.run(P.java:426) ~[Brewery-3.1.1.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1726) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[12:34:22] [Server thread/WARN]: [Brewery] Task #180 for Brewery v3.1.1 generated an exception
java.lang.IllegalArgumentException: missing required data class org.bukkit.Color
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:218) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.craftbukkit.CraftParticle.createParticleParam(CraftParticle.java:68) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at org.bukkit.craftbukkit.CraftWorld.spawnParticle(CraftWorld.java:2181) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at org.bukkit.craftbukkit.CraftWorld.spawnParticle(CraftWorld.java:2169) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at org.bukkit.craftbukkit.CraftWorld.spawnParticle(CraftWorld.java:2158) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at org.bukkit.craftbukkit.CraftWorld.spawnParticle(CraftWorld.java:2148) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at org.bukkit.craftbukkit.CraftWorld.spawnParticle(CraftWorld.java:2143) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at Brewery-3.1.1.jar/com.dre.brewery.BCauldron.cookEffect(BCauldron.java:257) ~[Brewery-3.1.1.jar:?]
```

**Comment by Savranchuk** [comment]
and i have this problem

`        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1335) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[11:04:51 WARN]: [Brewery] Task #67 for Brewery v3.1.1 generated an exception
java.lang.IllegalArgumentException: missing required data class org.bukkit.Color
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:218) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.craftbukkit.CraftParticle.createParticleParam(CraftParticle.java:68) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at org.bukkit.craftbukkit.CraftWorld.spawnParticle(CraftWorld.java:2171) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at org.bukkit.craftbukkit.CraftWorld.spawnParticle(CraftWorld.java:2159) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at org.bukkit.craftbukkit.CraftWorld.spawnParticle(CraftWorld.java:2148) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at org.bukkit.craftbukkit.CraftWorld.spawnParticle(CraftWorld.java:2138) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at org.bukkit.craftbukkit.CraftWorld.spawnParticle(CraftWorld.java:2133) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at Brewery-3.1.1.jar/com.dre.brewery.BCauldron.cookEffect(BCauldron.java:257) ~[Brewery-3.1.1.jar:?]
        at Brewery-3.1.1.jar/com.dre.brewery.BCauldron.processCookEffects(BCauldron.java:375) ~[Brewery-3.1.1.jar:?]
        at Brewery-3.1.1.jar/com.dre.brewery.P$CauldronParticles.run(P.java:426) ~[Brewery-3.1.1.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1763) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:513) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1635) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1335) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]`

**Comment by Nadwey** [comment]
Fixed in [BreweryX](https://modrinth.com/plugin/breweryx)
